### ISSUE TITLE
Travis build failing.

### ISSUE THREAD

**Issue by idealadarsh** [idealadarsh/MomentOfInertia#3]
Please check the Travis build log for a detailed information.
https://travis-ci.org/idealadarsh/MomentOfInertia/builds/288888059

**Comment by JeffreyCA** [comment]
Try updating `ANDROID_BUILD_TOOLS` to 21.1.2.

**Comment by idealadarsh** [comment]
@JeffreyCA Thanks, I think this issue can be closed now.
